### ISSUE TITLE
Add a parser utility

### ISSUE THREAD

**Issue by oppahansi** [oppahansi/WowCoordinatesToSQLPaths#1]
**Add a Parser to the project.**

-  Suggesting adding new Folder, name it in a descriptive way like Tools, Utils ...
- Add a class that provides static methods to parse different kind of files. Name the class Parser or if you have a better name, name it your way.
 
For now we should consider being able to parse `CSV` (, or ; delimeters) and our own `wow addon log files`.
Example data will be attached here to a later point. 

We should have some methods that can return lists of predifned row objects like
`List<CreatureMovementRow>`
`List<CreatureMovementTemplateRow>`
`List<ScriptWaypointRow>`

Using our wow addon log file or a CSV file.

**Comment by oppahansi** [comment]
Example addon log data added. In resources folder.

**Comment by KianFitz** [comment]
Created simple Lua parser and used example data for testing. Anchored all menus.
